/**
 * Renders the shared schema to schema.sql for `wrangler d1 execute`.
 *
 * A Worker cannot create its own tables on a cold start without racing every
 * other in-flight request, so D1 migrations are applied out of band — but the
 * statements still come from the one definition in @fc/server.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const { SCHEMA, MIGRATIONS } = await import("@fc/server/store/schema");

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(here, "../schema.sql");

const sql = [
  "-- Generated by `npm run schema -w @fc/worker` — do not edit.",
  "-- Source: packages/server/src/store/schema.ts",
  "",
  ...SCHEMA.map((statement) => `${statement.trim()};`),
  "",
  "-- Migrations for databases created by an earlier version. These fail",
  "-- harmlessly with \"duplicate column\" on a database built from the schema",
  "-- above, which already includes them.",
  ...MIGRATIONS.map((statement) => `${statement.trim()};`),
  "",
].join("\n");

fs.writeFileSync(out, sql);
console.log(`Wrote ${out} (${SCHEMA.length} statements)`);
